# Generated by Django 5.2.3 on 2025-06-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cpf",
            fields=[
                (
                    "cpf",
                    models.CharField(
                        db_index=True, max_length=14, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=255)),
                ("nasc", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "cpf",
            },
        ),
    ]
